[package]
name = "aoc2021"
version = "0.1.0"
authors = ["Justin Kaufman <akaritakai@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
reqwest = { version = "0.11.7", features = ["blocking"] }
regex = "1.5.4"

[dev-dependencies]
httpmock = "0.6.4"
rand = "0.8.4"
tempfile = "3.2.0"